<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Paynl\Payment\Block\Page\FastCheckoutFallback */
?>
<div class="paynl-fast_checkout" data-mage-init='{"Paynl_Payment/js/reloadCart": {}}'>
    <p><?= $block->escapeHtml(__('Please select your shipping method:')) ?></p>
    <br/>

    <form action="<?= $block->escapeUrl($block->getUrl('paynl/checkout/fastcheckoutstart')) ?>"
          id="paynl_fast_checkout_fallback"
          method="post">

        <?php foreach ($block->getShippingMethods() as $key => $method) : ?>
            <div style="margin-bottom:15px;">
                <input type="radio"
                       class="radio"
                       value="<?= $block->escapeHtmlAttr($method->code) ?>"
                       id="<?= $block->escapeHtmlAttr($method->code) ?>"
                       name="fallbackShippingMethod">
                <label for="<?= $block->escapeHtmlAttr($method->code) ?>">
                    <?= $block->escapeHtml($method->method) ?>:
                    <?= $block->escapeHtml($method->title) ?>
                    <b><?= $block->escapeHtml($method->currency) ?><?= $block->escapeHtml($method->price) ?></b>
                </label>
            </div>
        <?php endforeach; ?>

        <br/>
        <button type="submit"
                title="<?= $block->escapeHtmlAttr(__('Fast Checkout')) ?>"
                class="action tocart primary paynl-fast_checkout-btn checkout">
            <span><?= $block->escapeHtml(__('Continue')) ?></span>
        </button>
    </form>
</div>
