<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Paynl\Payment\Block\Page\Finish */
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()): ?>
            <p>
                <?= $block->escapeHtml(__('Your order number is:')) ?>
                <?= /* @noEscape */ sprintf(
                    '<a href="%s" class="order-number"><strong>%s</strong></a>',
                    $block->escapeUrl($block->getViewOrderUrl()),
                    $block->escapeHtml($block->getOrderId())
                ) ?>
            </p>
        <?php else: ?>
            <p>
                <?= /* @noEscape */ sprintf(
                    $block->escapeHtml(__('Your order # is: <span>%1</span>.')),
                    $block->escapeHtml($block->getOrderId())
                ) ?>
            </p>
        <?php endif; ?>
        <p>
            <?= $block->escapeHtml(__("We'll email you an order confirmation with details and tracking info.")) ?>
        </p>
    <?php endif; ?>

    <?= /* @noEscape */ $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
