<?php
/** @var \Paynl\Payment\Block\Checkout\FastCheckout $block */
    $viewModel = $block->getViewModel();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Paynl_Payment/js/fast-checkout": {
                "minicartEnabled": <?= $viewModel->minicartEnabled() ? 'true' : 'false' ?>,
                "modalEnabled": <?= $viewModel->modalEnabled() ? 'true' : 'false' ?>
            }
        }
    }
</script>