
<?php
/** @var \Paynl\Payment\Block\Checkout\FastCheckout $block */
?>

<div id="paynl_fast_checkout_product" data-mage-init='{"Paynl_Payment/js/reloadCart": {}}'>
    <button type="submit"
            title="Fast Checkout"
            class="action primary paynl-fast-checkout-btn tocart"
            data-mage-init='{"Paynl_Payment/js/fast-checkout-product-view": {}}'>
        <span><?= /* @escapeNotVerified */ __('Fast Checkout') ?></span>
    </button>
</div>