
<?php
/** @var \Paynl\Payment\Block\Checkout\FastCheckout $block */
?>

<div class="paynl-fast_checkout">
    <form action="/paynl/checkout/fastcheckoutstart" id="paynl_fast_checkout_cart" method="post">
        <button type="submit"
                title="Fast Checkout"
                class="action tocart primary paynl-fast_checkout-btn">
            <span>Fast Checkout</span>
        </button>
    </form>
</div>
