
<?php
/** @var \Paynl\Payment\Block\Checkout\QuickCheckout $block */
?>

<div class="paynl-quick_checkout">
    <form action="/paynl/checkout/fastcheckoutstart" id="paynl_quick_checkout_cart" method="post">            
        <button type="submit"
                title="Quick Checkout"
                class="action tocart primary paynl-quick_checkout-btn">
            <span>Quick Checkout</span>
        </button>
    </form>
</div>
