<?php

/**
 * @var \Paynl\Payment\Block\Display $block
 */

?>
<div class="checkout-success">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">
            <?php
            $cancel = $block->getParam('cancel');

            $message = __('Thank you for your purchase!');
            if ($cancel == 1) {
                $message = __('The payment has been canceled.');
            }
            echo $block->escapeHtml($message);
            ?>
        </span>
    </h1>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
        </div>
    </div>
</div>