<?php
// @codingStandardsIgnoreFile
/**
 * @var $block Paynl\Payment\Block\Adminhtml\Order\View\View
 */
?>
<div class="admin__page-section-item pay-orderinformation">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @noEscape */__("Pay. Orderinformation") ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <table class="admin__table-secondary order-information-table">
            <tbody>
            <tr>
                <th><?= /* @noEscape */__("Payment method") ?></th>
                <td><?php echo $block->getPaymentMethod()?></td>
            </tr>
            <tr>
                <th><?= /* @noEscape */__("Pay. Transaction-ID") ?></th>
                <td><a href="<?php echo $block->getPayUrl()?>" target="_blank"><?php echo $block->getId()?><span class="pay-link-icon">&#129149;</span></a></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>