<?php
/**
 * @var $block Paynl\Payment\Block\Adminhtml\Order\View\View
 */
?>
<div class="admin__page-section-item pay-orderinformation">
    <div class="admin__page-section-item-content">
        <?= $block->escapeHtml(__('Pay. transaction-ID: ')) ?>
        <a href="<?= $block->escapeUrl($block->getPayUrl()) ?>" target="_blank">
            <?= $block->escapeHtml($block->getId()) ?>
            <span class="pay-link-icon">&#11016;</span>
        </a>
    </div>
</div>
