<?php
// @codingStandardsIgnoreFile
/**
 * @var $block Paynl\Payment\Block\Adminhtml\Order\View\View
 */
?>
<div class="admin__page-section-item pay-orderinformation">
    <div class="admin__page-section-item-content">
        <?= /* @noEscape */
        __("Pay. Transaction-ID: ") ?><a href="<?php echo $block->getPayUrl() ?>"
                                         target="_blank"><?php echo $block->getId() ?><span class="pay-link-icon">&#11016;</span></a>
    </div>
</div>