<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Paynl\Payment\Block\Form\Paylink */

$code = $block->getMethodCode(); // nog niet escapen hier, pas in de HTML zelf
$terminals = $block->getTerminals();
$defaultTerminal = $block->getDefaultTerminal();
$hidePaymentOptions = $block->hidePaymentOptions();

?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= $block->escapeHtmlAttr($code) ?>"
          style="display:none;">
    <?php if ($hidePaymentOptions == 1) : ?>
        <input type="hidden"
               id="<?= $block->escapeHtmlAttr($code) ?>_payment_option"
               name="payment[payment_option]"
               value="<?= $block->escapeHtmlAttr($defaultTerminal) ?>" />
    <?php else : ?>
        <div class="admin__field">
            <label for="<?= $block->escapeHtmlAttr($code) ?>_payment_option"
                   class="admin__field-label">
                <?= $block->escapeHtml(__('Terminal')) ?>:
            </label>
            <div class="admin__field-control">
                <select class="admin__control-select"
                        id="<?= $block->escapeHtmlAttr($code) ?>_payment_option"
                        name="payment[payment_option]">
                    <?php foreach ($terminals as $key => $terminal) : ?>
                        <option value="<?= $block->escapeHtmlAttr($key) ?>"
                            <?= ($key == $defaultTerminal) ? 'selected' : '' ?>>
                            <?= $block->escapeHtml($terminal) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
