<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Paynl\Payment\Block\Adminhtml\Render\Credentials
 */

$status = $block->checkCredentials();

?>

<?php if ($status['status'] == 1) : ?>
    <span class="value pay_connect_success"><?= __('Pay. successfully connected') ?> </span>
<?php elseif (!empty($status['error'])) : ?>
    <span class="value pay_connect_failure"><?= __('Pay. connection failed') ?> (<?= $status['error'] ?>) </span>
<?php else : ?>
    <span class="value pay_connect_empty"><?= __('Pay. not connected') ?> </span>
<?php endif; ?>