<?php

/**
 * @see \Paynl\Payment\Block\Adminhtml\System\Config\Form\Credentials\Checker
 * @var \Paynl\Payment\Block\Adminhtml\System\Config\Form\Credentials\Checker $block
 */
?>
<script>
    require([
        'jquery'
    ], function(jQuery) {
        jQuery('#test_credentials').click(function() {
            var params = {
                'tokencode': jQuery("#paynl_setup_paynl_general_settings_tokencode").val(),
                'apitoken': jQuery("#paynl_setup_paynl_general_settings_apitoken").val(),
                'serviceid': jQuery("#paynl_setup_paynl_general_settings_serviceid").val(),
                'scope': '<?php echo $block->getScope()['scope']; ?>',
                'scopeid': '<?php echo $block->getScope()['scopeId']; ?>'
            }
            new Ajax.Request('<?= $block->getAjaxUrl() ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {                
                    jQuery('#paynl_test_credentials_result').hide();
                    jQuery('#paynl_test_credentials_loading').show();
                },
                onSuccess: function(response) {
                    var json = response.responseJSON;           
                    if (json.status == 1) {
                        var resultText = '  <span style="color:#10723a; font-weight: bold">Pay. Successfully connected.</span>';
                    } else if (json.error.length > 0) {
                        var resultText = '  <span style="color:#f00; font-weight: bold">Pay. Connection failed. (' + json.error + ')</span>';
                    } 
                    jQuery('#paynl_test_credentials_result').html(resultText);
                    jQuery('#paynl_test_credentials_result').show();
                    jQuery('#paynl_test_credentials_loading').hide();
                }
            });
        });
    });
</script>
<?= $block->getButtonHtml() ?>