<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Paynl\Payment\Block\Adminhtml\Render\Credentials
 */

$status = $block->checkCredentials();

?>

<?php if ($status['status'] == 1) : ?>
    <span class="value" style="color:#10723a; font-weight: bold"><?= __('Pay. Successfully connected.') ?> </span>
<?php elseif (!empty($status['error'])) : ?>
    <span class="value" style="color:#f00; font-weight: bold"><?= __('Pay. Connection failed.') ?> (<?= $status['error'] ?>) </span>
<?php else : ?>
    <span class="value" style="color:#ff8300; font-weight: bold"><?= __('Pay. Not connected.') ?> </span>
<?php endif; ?>