<button id="inactive-methods-button" title="<?= $block->escapeHtml(__('Show all payment methods')) ?>" type="button"
    class="action-default primary">
    <span><?= $block->escapeHtml(__('Show all payment methods')) ?></span>
</button>

<button id="inactive-methods-button-hide" title="<?= $block->escapeHtml(__('Hide inactive payment methods')) ?>" type="button"
    class="action-default primary">
    <span><?= $block->escapeHtml(__('Hide inactive payment methods')) ?></span>
</button>