<button id="inactive-methods-button" title="<?= __('Show all payment methods') ?>" type="button"
    class="action-default primary">
    <span><?= __('Show all payment methods') ?></span>
</button>

<button id="inactive-methods-button-hide" title="<?= __('Hide inactive payment methods') ?>" type="button"
    class="action-default primary">
    <span><?= __('Hide inactive payment methods') ?></span>
</button>