<?php $element = $this->getData('element'); ?>

<span class="multiselectPay">
    <input type="hidden"
           id="<?= $block->escapeHtmlAttr($element->getHtmlId()) ?>"
           name="<?= $block->escapeHtmlAttr($element->getName()) ?>"
           value="<?= $block->escapeHtmlAttr($element->getValue()) ?>" />
    <span class="ms_options">
        <?php foreach ($element->getValues() as $value):
            if (!empty($value) && !empty($value['value'])):
                if (isset($value['is_region_visible']) && $value['is_region_visible'] === false):
                    continue;
                endif;

                if (is_array($value['value'])):
                    $label = $block->escapeHtml($value['label']);
                    $multiValues = $value['value'];
                    $option = '<optgroup label="' . $label . '">';
                    foreach ($multiValues as $multiValue) {
                        $selected = in_array($multiValue['value'], explode(',', $element->getValue() ?? '')) ? 'selected' : '';
                        $option .= '<option class="' . $block->escapeHtmlAttr($selected) . '" value="' . $block->escapeHtmlAttr($multiValue['value']) . '">' . $block->escapeHtml($multiValue['label']) . '</option>';
                    }
                    $option .= '</optgroup>';
                else:
                    $selected = in_array($value['value'], explode(',', $element->getValue() ?? '')) ? 'selected' : '';
                    $option = '<option class="' . $block->escapeHtmlAttr($selected) . '" value="' . $block->escapeHtmlAttr($value['value']) . '">' . $block->escapeHtml($value['label']) . '</option>';
                endif;
                ?>
                <?= /* @noEscape */ $option ?>
            <?php
            endif;
        endforeach; ?>
    </span>
</span>

<script type="text/x-magento-init">
    {
        "*": {
            "Paynl_Payment/js/multiselect" : {
                "element" : "<?= $block->escapeJs($element->getHtmlId()) ?>"
            }
        }
    }
</script>
