<?php
/**
 * @see \Paynl\Payment\Block\Adminhtml\Render\Version
 * @var \Paynl\Payment\Block\Adminhtml\Render\Version $block
 */
?>
<span id="paynl_version_check_current_version">
    <?= $block->escapeHtml($block->getVersion()) ?>
</span>

<?= $block->getButtonHtml() ?>

<span id="paynl_version_check_text">
    <span id="paynl_version_check_loading" class="paynl_hidden">
        <?= $block->escapeHtml(__('Loading...')) ?>
    </span>
    <span id="paynl_version_check_result" class="paynl_hidden"></span>
</span>

<span class="paynl_hidden">
    <span id="ajaxurl"><?= $block->escapeUrl($block->getAjaxUrl()) ?></span>
    <span id="current_version"><?= $block->escapeHtml($block->getVersion()) ?></span>
    <span id="VC_version_check_result_success">
        <?= $block->escapeHtml(__('You are up to date with the latest version')) ?>
    </span>
</span>

<link rel="stylesheet" type="text/css"
      href="<?= $block->escapeUrl($block->getViewFileUrl('Paynl_Payment::css/versioncheck.css')) ?>">

<script type="text/x-magento-init">
    {
        "*": {
            "Paynl_Payment/js/versioncheck": {}
        }
    }
</script>
