<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Magento\Sales\Block\Adminhtml\Order\Creditmemo\Create\Items $block */
?>
<?php
/** @var Magento\Sales\ViewModel\CreditMemo\Create\UpdateTotalsButton $viewModel */
$viewModel = $block->getData('viewModel');

?>

<script>
require(['jquery', 'Magento_Ui/js/modal/confirm'], function(jQuery, confirmation){

//<![CDATA[
confrimBox = function(title, text, $alias) {
    confirmation({
        title: title,
        content: text,
        actions: {
            confirm: function(){
                disableElements($alias);
                submitCreditMemoOffline();
                return true;
            },
            cancel: function(){
                return false;
            },
            always: function(){}
        }
    })
    return false;
}
//]]>
});
</script>
